// Country data with codes and names
// Flag emoji/icons to be replaced with local image assets

export interface Country {
  code: string;
  name: string;
  flag: any; // require() result (image module)
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', flag: require('../assets/flags/af.png') },
  { code: 'AL', name: 'Albania', flag: require('../assets/flags/al.png') },
  { code: 'DZ', name: 'Algeria', flag: require('../assets/flags/dz.png') },
  { code: 'AR', name: 'Argentina', flag: require('../assets/flags/ar.png') },
  { code: 'AM', name: 'Armenia', flag: require('../assets/flags/am.png') },
  { code: 'AU', name: 'Australia', flag: require('../assets/flags/au.png') },
  { code: 'AT', name: 'Austria', flag: require('../assets/flags/at.png') },
  { code: 'AZ', name: 'Azerbaijan', flag: require('../assets/flags/az.png') },
  { code: 'BH', name: 'Bahrain', flag: require('../assets/flags/bh.png') },
  { code: 'BD', name: 'Bangladesh', flag: require('../assets/flags/bd.png') },
  { code: 'BY', name: 'Belarus', flag: require('../assets/flags/by.png') },
  { code: 'BE', name: 'Belgium', flag: require('../assets/flags/be.png') },
  { code: 'BZ', name: 'Belize', flag: require('../assets/flags/bz.png') },
  { code: 'BJ', name: 'Benin', flag: require('../assets/flags/bj.png') },
  { code: 'BT', name: 'Bhutan', flag: require('../assets/flags/bt.png') },
  { code: 'BO', name: 'Bolivia', flag: require('../assets/flags/bo.png') },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: require('../assets/flags/ba.png') },
  { code: 'BW', name: 'Botswana', flag: require('../assets/flags/bw.png') },
  { code: 'BR', name: 'Brazil', flag: require('../assets/flags/br.png') },
  { code: 'BN', name: 'Brunei', flag: require('../assets/flags/bn.png') },
  { code: 'BG', name: 'Bulgaria', flag: require('../assets/flags/bg.png') },
  { code: 'BF', name: 'Burkina Faso', flag: require('../assets/flags/bf.png') },
  { code: 'BI', name: 'Burundi', flag: require('../assets/flags/bi.png') },
  { code: 'KH', name: 'Cambodia', flag: require('../assets/flags/kh.png') },
  { code: 'CM', name: 'Cameroon', flag: require('../assets/flags/cm.png') },
  { code: 'CA', name: 'Canada', flag: require('../assets/flags/ca.png') },
  { code: 'CV', name: 'Cape Verde', flag: require('../assets/flags/cv.png') },
  { code: 'CF', name: 'Central African Republic', flag: require('../assets/flags/cf.png') },
  { code: 'TD', name: 'Chad', flag: require('../assets/flags/td.png') },
  { code: 'CL', name: 'Chile', flag: require('../assets/flags/cl.png') },
  { code: 'CN', name: 'China', flag: require('../assets/flags/cn.png') },
  { code: 'CO', name: 'Colombia', flag: require('../assets/flags/co.png') },
  { code: 'KM', name: 'Comoros', flag: require('../assets/flags/km.png') },
  { code: 'CG', name: 'Congo', flag: require('../assets/flags/cg.png') },
  { code: 'CR', name: 'Costa Rica', flag: require('../assets/flags/cr.png') },
  { code: 'HR', name: 'Croatia', flag: require('../assets/flags/hr.png') },
  { code: 'CU', name: 'Cuba', flag: require('../assets/flags/cu.png') },
  { code: 'CY', name: 'Cyprus', flag: require('../assets/flags/cy.png') },
  { code: 'CZ', name: 'Czech Republic', flag: require('../assets/flags/cz.png') },
  { code: 'DK', name: 'Denmark', flag: require('../assets/flags/dk.png') },
  { code: 'DJ', name: 'Djibouti', flag: require('../assets/flags/dj.png') },
  { code: 'DO', name: 'Dominican Republic', flag: require('../assets/flags/do.png') },
  { code: 'EC', name: 'Ecuador', flag: require('../assets/flags/ec.png') },
  { code: 'EG', name: 'Egypt', flag: require('../assets/flags/eg.png') },
  { code: 'SV', name: 'El Salvador', flag: require('../assets/flags/sv.png') },
  { code: 'GQ', name: 'Equatorial Guinea', flag: require('../assets/flags/gq.png') },
  { code: 'ER', name: 'Eritrea', flag: require('../assets/flags/er.png') },
  { code: 'EE', name: 'Estonia', flag: require('../assets/flags/ee.png') },
  { code: 'ET', name: 'Ethiopia', flag: require('../assets/flags/et.png') },
  { code: 'FJ', name: 'Fiji', flag: require('../assets/flags/fj.png') },
  { code: 'FI', name: 'Finland', flag: require('../assets/flags/fi.png') },
  { code: 'FR', name: 'France', flag: require('../assets/flags/fr.png') },
  { code: 'GA', name: 'Gabon', flag: require('../assets/flags/ga.png') },
  { code: 'GM', name: 'Gambia', flag: require('../assets/flags/gm.png') },
  { code: 'GE', name: 'Georgia', flag: require('../assets/flags/ge.png') },
  { code: 'DE', name: 'Germany', flag: require('../assets/flags/de.png') },
  { code: 'GH', name: 'Ghana', flag: require('../assets/flags/gh.png') },
  { code: 'GR', name: 'Greece', flag: require('../assets/flags/gr.png') },
  { code: 'GT', name: 'Guatemala', flag: require('../assets/flags/gt.png') },
  { code: 'GN', name: 'Guinea', flag: require('../assets/flags/gn.png') },
  { code: 'GW', name: 'Guinea-Bissau', flag: require('../assets/flags/gw.png') },
  { code: 'GY', name: 'Guyana', flag: require('../assets/flags/gy.png') },
  { code: 'HT', name: 'Haiti', flag: require('../assets/flags/ht.png') },
  { code: 'HN', name: 'Honduras', flag: require('../assets/flags/hn.png') },
  { code: 'HU', name: 'Hungary', flag: require('../assets/flags/hu.png') },
  { code: 'IS', name: 'Iceland', flag: require('../assets/flags/is.png') },
  { code: 'IN', name: 'India', flag: require('../assets/flags/in.png') },
  { code: 'ID', name: 'Indonesia', flag: require('../assets/flags/id.png') },
  { code: 'IR', name: 'Iran', flag: require('../assets/flags/ir.png') },
  { code: 'IQ', name: 'Iraq', flag: require('../assets/flags/iq.png') },
  { code: 'IE', name: 'Ireland', flag: require('../assets/flags/ie.png') },
  { code: 'IL', name: 'Israel', flag: require('../assets/flags/il.png') },
  { code: 'IT', name: 'Italy', flag: require('../assets/flags/it.png') },
  { code: 'JM', name: 'Jamaica', flag: require('../assets/flags/jm.png') },
  { code: 'JP', name: 'Japan', flag: require('../assets/flags/jp.png') },
  { code: 'JO', name: 'Jordan', flag: require('../assets/flags/jo.png') },
  { code: 'KZ', name: 'Kazakhstan', flag: require('../assets/flags/kz.png') },
  { code: 'KE', name: 'Kenya', flag: require('../assets/flags/ke.png') },
  { code: 'KI', name: 'Kiribati', flag: require('../assets/flags/ki.png') },
  { code: 'KW', name: 'Kuwait', flag: require('../assets/flags/kw.png') },
  { code: 'KG', name: 'Kyrgyzstan', flag: require('../assets/flags/kg.png') },
  { code: 'LA', name: 'Laos', flag: require('../assets/flags/la.png') },
  { code: 'LV', name: 'Latvia', flag: require('../assets/flags/lv.png') },
  { code: 'LB', name: 'Lebanon', flag: require('../assets/flags/lb.png') },
  { code: 'LS', name: 'Lesotho', flag: require('../assets/flags/ls.png') },
  { code: 'LR', name: 'Liberia', flag: require('../assets/flags/lr.png') },
  { code: 'LY', name: 'Libya', flag: require('../assets/flags/ly.png') },
  { code: 'LI', name: 'Liechtenstein', flag: require('../assets/flags/li.png') },
  { code: 'LT', name: 'Lithuania', flag: require('../assets/flags/lt.png') },
  { code: 'LU', name: 'Luxembourg', flag: require('../assets/flags/lu.png') },
  { code: 'MG', name: 'Madagascar', flag: require('../assets/flags/mg.png') },
  { code: 'MW', name: 'Malawi', flag: require('../assets/flags/mw.png') },
  { code: 'MY', name: 'Malaysia', flag: require('../assets/flags/my.png') },
  { code: 'MV', name: 'Maldives', flag: require('../assets/flags/mv.png') },
  { code: 'ML', name: 'Mali', flag: require('../assets/flags/ml.png') },
  { code: 'MT', name: 'Malta', flag: require('../assets/flags/mt.png') },
  { code: 'MH', name: 'Marshall Islands', flag: require('../assets/flags/mh.png') },
  { code: 'MR', name: 'Mauritania', flag: require('../assets/flags/mr.png') },
  { code: 'MU', name: 'Mauritius', flag: require('../assets/flags/mu.png') },
  { code: 'MX', name: 'Mexico', flag: require('../assets/flags/mx.png') },
  { code: 'FM', name: 'Micronesia', flag: require('../assets/flags/fm.png') },
  { code: 'MD', name: 'Moldova', flag: require('../assets/flags/md.png') },
  { code: 'MC', name: 'Monaco', flag: require('../assets/flags/mc.png') },
  { code: 'MN', name: 'Mongolia', flag: require('../assets/flags/mn.png') },
  { code: 'ME', name: 'Montenegro', flag: require('../assets/flags/me.png') },
  { code: 'MA', name: 'Morocco', flag: require('../assets/flags/ma.png') },
  { code: 'MZ', name: 'Mozambique', flag: require('../assets/flags/mz.png') },
  { code: 'MM', name: 'Myanmar', flag: require('../assets/flags/mm.png') },
  { code: 'NA', name: 'Namibia', flag: require('../assets/flags/na.png') },
  { code: 'NR', name: 'Nauru', flag: require('../assets/flags/nr.png') },
  { code: 'NP', name: 'Nepal', flag: require('../assets/flags/np.png') },
  { code: 'NL', name: 'Netherlands', flag: require('../assets/flags/nl.png') },
  { code: 'NZ', name: 'New Zealand', flag: require('../assets/flags/nz.png') },
  { code: 'NI', name: 'Nicaragua', flag: require('../assets/flags/ni.png') },
  { code: 'NE', name: 'Niger', flag: require('../assets/flags/ne.png') },
  { code: 'NG', name: 'Nigeria', flag: require('../assets/flags/ng.png') },
  { code: 'KP', name: 'North Korea', flag: require('../assets/flags/kp.png') },
  { code: 'MK', name: 'North Macedonia', flag: require('../assets/flags/mk.png') },
  { code: 'NO', name: 'Norway', flag: require('../assets/flags/no.png') },
  { code: 'OM', name: 'Oman', flag: require('../assets/flags/om.png') },
  { code: 'PK', name: 'Pakistan', flag: require('../assets/flags/pk.png') },
  { code: 'PW', name: 'Palau', flag: require('../assets/flags/pw.png') },
  { code: 'PS', name: 'Palestine', flag: require('../assets/flags/ps.png') },
  { code: 'PA', name: 'Panama', flag: require('../assets/flags/pa.png') },
  { code: 'PG', name: 'Papua New Guinea', flag: require('../assets/flags/pg.png') },
  { code: 'PY', name: 'Paraguay', flag: require('../assets/flags/py.png') },
  { code: 'PE', name: 'Peru', flag: require('../assets/flags/pe.png') },
  { code: 'PH', name: 'Philippines', flag: require('../assets/flags/ph.png') },
  { code: 'PL', name: 'Poland', flag: require('../assets/flags/pl.png') },
  { code: 'PT', name: 'Portugal', flag: require('../assets/flags/pt.png') },
  { code: 'QA', name: 'Qatar', flag: require('../assets/flags/qa.png') },
  { code: 'RO', name: 'Romania', flag: require('../assets/flags/ro.png') },
  { code: 'RU', name: 'Russia', flag: require('../assets/flags/ru.png') },
  { code: 'RW', name: 'Rwanda', flag: require('../assets/flags/rw.png') },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: require('../assets/flags/kn.png') },
  { code: 'LC', name: 'Saint Lucia', flag: require('../assets/flags/lc.png') },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: require('../assets/flags/vc.png') },
  { code: 'WS', name: 'Samoa', flag: require('../assets/flags/ws.png') },
  { code: 'SM', name: 'San Marino', flag: require('../assets/flags/sm.png') },
  { code: 'ST', name: 'Sao Tome and Principe', flag: require('../assets/flags/st.png') },
  { code: 'SA', name: 'Saudi Arabia', flag: require('../assets/flags/sa.png') },
  { code: 'SN', name: 'Senegal', flag: require('../assets/flags/sn.png') },
  { code: 'RS', name: 'Serbia', flag: require('../assets/flags/rs.png') },
  { code: 'SC', name: 'Seychelles', flag: require('../assets/flags/sc.png') },
  { code: 'SL', name: 'Sierra Leone', flag: require('../assets/flags/sl.png') },
  { code: 'SG', name: 'Singapore', flag: require('../assets/flags/sg.png') },
  { code: 'SK', name: 'Slovakia', flag: require('../assets/flags/sk.png') },
  { code: 'SI', name: 'Slovenia', flag: require('../assets/flags/si.png') },
  { code: 'SB', name: 'Solomon Islands', flag: require('../assets/flags/sb.png') },
  { code: 'SO', name: 'Somalia', flag: require('../assets/flags/so.png') },
  { code: 'ZA', name: 'South Africa', flag: require('../assets/flags/za.png') },
  { code: 'KR', name: 'South Korea', flag: require('../assets/flags/kr.png') },
  { code: 'SS', name: 'South Sudan', flag: require('../assets/flags/ss.png') },
  { code: 'ES', name: 'Spain', flag: require('../assets/flags/es.png') },
  { code: 'LK', name: 'Sri Lanka', flag: require('../assets/flags/lk.png') },
  { code: 'SD', name: 'Sudan', flag: require('../assets/flags/sd.png') },
  { code: 'SR', name: 'Suriname', flag: require('../assets/flags/sr.png') },
  { code: 'SE', name: 'Sweden', flag: require('../assets/flags/se.png') },
  { code: 'CH', name: 'Switzerland', flag: require('../assets/flags/ch.png') },
  { code: 'SY', name: 'Syria', flag: require('../assets/flags/sy.png') },
  { code: 'TW', name: 'Taiwan', flag: require('../assets/flags/tw.png') },
  { code: 'TJ', name: 'Tajikistan', flag: require('../assets/flags/tj.png') },
  { code: 'TZ', name: 'Tanzania', flag: require('../assets/flags/tz.png') },
  { code: 'TH', name: 'Thailand', flag: require('../assets/flags/th.png') },
  { code: 'TL', name: 'Timor-Leste', flag: require('../assets/flags/tl.png') },
  { code: 'TG', name: 'Togo', flag: require('../assets/flags/tg.png') },
  { code: 'TO', name: 'Tonga', flag: require('../assets/flags/to.png') },
  { code: 'TT', name: 'Trinidad and Tobago', flag: require('../assets/flags/tt.png') },
  { code: 'TN', name: 'Tunisia', flag: require('../assets/flags/tn.png') },
  { code: 'TR', name: 'Turkey', flag: require('../assets/flags/tr.png') },
  { code: 'TM', name: 'Turkmenistan', flag: require('../assets/flags/tm.png') },
  { code: 'TV', name: 'Tuvalu', flag: require('../assets/flags/tv.png') },
  { code: 'UG', name: 'Uganda', flag: require('../assets/flags/ug.png') },
  { code: 'UA', name: 'Ukraine', flag: require('../assets/flags/ua.png') },
  { code: 'AE', name: 'United Arab Emirates', flag: require('../assets/flags/ae.png') },
  { code: 'GB', name: 'United Kingdom', flag: require('../assets/flags/gb.png') },
  { code: 'US', name: 'United States', flag: require('../assets/flags/us.png') },
  { code: 'UY', name: 'Uruguay', flag: require('../assets/flags/uy.png') },
  { code: 'UZ', name: 'Uzbekistan', flag: require('../assets/flags/uz.png') },
  { code: 'VU', name: 'Vanuatu', flag: require('../assets/flags/vu.png') },
  { code: 'VA', name: 'Vatican City', flag: require('../assets/flags/va.png') },
  { code: 'VE', name: 'Venezuela', flag: require('../assets/flags/ve.png') },
  { code: 'VN', name: 'Vietnam', flag: require('../assets/flags/vn.png') },
  { code: 'YE', name: 'Yemen', flag: require('../assets/flags/ye.png') },
  { code: 'ZM', name: 'Zambia', flag: require('../assets/flags/zm.png') },
  { code: 'ZW', name: 'Zimbabwe', flag: require('../assets/flags/zw.png') },
];

export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find(c => c.code === code);
};

export const getCountryByName = (name: string): Country | undefined => {
  return COUNTRIES.find(c => c.name.toLowerCase() === name.toLowerCase());
};
